# The Minecraft version the Parchment version is for
neogradle.subsystems.parchment.minecraftVersion=1.21.1
# The version of the Parchment mappings
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
neo_version=21.1.97
jei_version=19.18.10.218
cloth_config_neoforge=15.0.140
embeddedt_id=5681729
carry_on_id=5649344
player_animation_lib=2.0.1+1.21.1
create_version = 0.5.1.j-55
flywheel_version = 0.6.11-13
registrate_version = MC1.20-1.3.3