modLoader = "javafml"
loaderVersion = "[4,)"
license = "GPL3 / CC BY-NC-ND 4.0"

[[mixins]]
config="tacz.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mods]]
modId = "tacz"
version = "${file.jarVersion}"
displayName = "Timeless & Classics Guns: Zero"
logoFile = "logo.png"
updateJSONURL = ""
displayURL = ""
authors = "Serene Wave Studio | Timeless Squad"
description = '''
This is a mirror project of TACZ use neoforge mod loader in mc 1.21.1
'''

[[dependencies.tacz]]
modId = "neoforge"
type="required"
versionRange = "[21.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tacz]]
modId = "minecraft"
type="required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tacz]]
modId = "shouldersurfing"
type="optional"
versionRange = "[1.21-4.3.0,)"
ordering = "NONE"
side = "CLIENT"

[modproperties.tacz]
catalogueItemIcon = "tacz:gun_smith_table"